language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      script:
        - npm run build
        - npm run lint
        - npm run test
    - stage: deploy
      if: branch = master
      script: npm run deploy